# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f1cb46ad44d7f0a2e05749878d2bb5e9"
name = "discount-tiers"
handle = "discount-tiers-2"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "quickstart-9757cb94.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
